### ISSUE TITLE
Bug: Uses system-default nvim config directory on macOS

### ISSUE THREAD

**Issue by Azeirah** [Azeirah/nv#4]
I assume this is the case for every OS, but this would mean there can be conflicting configs

**Comment by HeitorAugustoLN** [comment]
Technically shouldn't happen, since nixvim adds this on top of the init.lua:

```lua
-- Ignore the user lua configuration
vim.opt.runtimepath:remove(vim.fn.stdpath("config")) -- ~/.config/nvim
vim.opt.runtimepath:remove(vim.fn.stdpath("config") .. "/after") -- ~/.config/nvim/after
```

**Comment by Azeirah** [comment]
Hmm, I'm not sure what happened here, I think I might've just been looking at it wrong. I'll open this back up if I see the problem concretely again, but I don't think this was quite right.
